Writable:
    LogLevel: INFO
Service:
    Host: localhost
    Port: 4000
    ServerBindAddr: ''
    StartupMsg: edgex-ui-go service started
    HealthCheckInterval: 10s
    MaxRequestSize: 0
    RequestTimeout: 5s
    ListenOptions:
        IdentityFile: "/mnt/v/temp/curlz.json"
        OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
        OpenZitiServiceName: "svc.ui-server"
    CORSConfiguration:
        EnableCORS: true
        CORSAllowCredentials: false
        CORSAllowedOrigin: "https://*.edgex.ziti"
        CORSAllowedMethods: "GET, POST, PUT, PATCH, DELETE"
        CORSAllowedHeaders: "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
        CORSExposeHeaders: "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
        CORSMaxAge: 3600
Clients:
    core-data:
        Protocol: http
        Host: "core-data.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.core-data"
    core-metadata:
        Protocol: http
        Host: "core-metadata.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.core-metadata"
    core-command:
        Protocol: http
        Host: "core-command.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.core-command"
    support-notifications:
        Protocol: http
        Host: "support-notifications.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.support-notifications"
    support-scheduler:
        Protocol: http
        Host: "support-scheduler.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.support-scheduler"
    rules-engine:
        Protocol: http
        Host: "rules-engine.edgex.ziti"
        Port: 80
        SecurityOptions:
            IdentityFile: "/mnt/v/temp/curlz.json"
            OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
            OpenZitiServiceName: "edgex.rules-engine"
Registry:
    Host: localhosta
    Port: 8500
    Type: consul
    ConfigRegistryStem: edgex/appservices/
    ServiceVersion: '2.0'
APIGateway:
    Server: core-data.edgex.ziti
    ApplicationPort: 80
    ApplicationPortSSL: 8443
